// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9id9pCb2h_QT0QcLqzJspyfAZEQ1wT4c',
    appId: '1:747424875838:web:7fb1f60fb243e3512ed86f',
    messagingSenderId: '747424875838',
    projectId: 'barav-quiz',
    authDomain: 'barav-quiz.firebaseapp.com',
    storageBucket: 'barav-quiz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKzpJKiNyDxRviHng4ZSk-3Dtb7-ChXh4',
    appId: '1:747424875838:android:3942b90fddd00f282ed86f',
    messagingSenderId: '747424875838',
    projectId: 'barav-quiz',
    storageBucket: 'barav-quiz.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHq07tON18qjrc0XeJ7jLWX5NkakrSYl8',
    appId: '1:747424875838:ios:16863833c831d1cf2ed86f',
    messagingSenderId: '747424875838',
    projectId: 'barav-quiz',
    storageBucket: 'barav-quiz.firebasestorage.app',
    androidClientId: '747424875838-4djqb7ibtg2s4pogokkp1tjdlmv3ca69.apps.googleusercontent.com',
    iosClientId: '747424875838-rprkmmjro9oimrsch6h7arbuo08fl271.apps.googleusercontent.com',
    iosBundleId: 'com.benaapp.baravquiz',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHq07tON18qjrc0XeJ7jLWX5NkakrSYl8',
    appId: '1:747424875838:ios:55b4bbd546e6c8be2ed86f',
    messagingSenderId: '747424875838',
    projectId: 'barav-quiz',
    storageBucket: 'barav-quiz.firebasestorage.app',
    androidClientId: '747424875838-oumtsp6om6d903ldcmjup68mmaum2r50.apps.googleusercontent.com',
    iosClientId: '747424875838-rilvl748tvfh8p9k61ii4iaot42f8nec.apps.googleusercontent.com',
    iosBundleId: 'com.karoxkhalis.baravQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9id9pCb2h_QT0QcLqzJspyfAZEQ1wT4c',
    appId: '1:747424875838:web:7a2e9e60de9e05932ed86f',
    messagingSenderId: '747424875838',
    projectId: 'barav-quiz',
    authDomain: 'barav-quiz.firebaseapp.com',
    storageBucket: 'barav-quiz.firebasestorage.app',
  );
}
